//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHotel.API.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHotel.API.Infrastructure.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, couldn&apos;t process the request..
        /// </summary>
        public static string GlobalExceptionTitle {
            get {
                return ResourceManager.GetString("GlobalExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t file the file representing an image..
        /// </summary>
        public static string ImageFileNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("ImageFileNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email or password is invalid.
        /// </summary>
        public static string InvalidPasswordExceptionTitle {
            get {
                return ResourceManager.GetString("InvalidPasswordExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t authorized to perform this operation..
        /// </summary>
        public static string MyUnauthorizedExceptionTitle {
            get {
                return ResourceManager.GetString("MyUnauthorizedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t found the demanded resource..
        /// </summary>
        public static string NotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("NotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t perfrom the demanded operation..
        /// </summary>
        public static string OperationFailedExceptionTitle {
            get {
                return ResourceManager.GetString("OperationFailedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coudln&apos;t create a payment..
        /// </summary>
        public static string PaymentNotCreatedExceptionTitle {
            get {
                return ResourceManager.GetString("PaymentNotCreatedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room is booked in the selected interval..
        /// </summary>
        public static string RoomAlreadyBookedExceptionTitle {
            get {
                return ResourceManager.GetString("RoomAlreadyBookedExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform that operation..
        /// </summary>
        public static string UnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified user is not found..
        /// </summary>
        public static string UserNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("UserNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified email is not found..
        /// </summary>
        public static string UserWithEmailNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("UserWithEmailNotFoundExceptionTitle", resourceCulture);
            }
        }
    }
}
